spring:
    datasource:
      platform: org.hibernate.dialect.MySQL5InnoDBDialect


    
    jpa:
      show-sql: false
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
              ddl-auto: 'none'
    main:
      banner-mode: CONSOLE

logging:
    level:
        org:
            hibernate:
              SQL: error
              type:
                descriptor:
                  sql: error
            springframework:
                web: info
                transaction: error
            thymeleaf: error
        com.witosmartyn.app:
            controllers: error
            config: error
            services: error
        root: info
    pattern:
     file: "%d %-5level [%thread] %logger : %msg%n"
